### ISSUE TITLE
celluloid and jupyter notebook

### ISSUE THREAD

**Issue by evgeniy97** [jwkvam/celluloid#7]
Hi!  
I wonder if celluloid is able to be used in Jupyter Notebook? I've tryied to run your example but it have not shown anything. Can I use celluloid and jupyter togheter?   
Thanks!

**Comment by jwkvam** [comment]
@evgeniy97 Thanks for the question, the answer is yes you can! Once you get the animation object you can view it in your notebook as follows:

```python
from IPython.display import HTML
anim = camera.animate()
HTML(anim.to_html5_video())
```

I'll add this snippet to the readme.

**Comment by jwkvam** [comment]
documented in https://github.com/jwkvam/celluloid/commit/037ed04de428fed6f82203446fe43d5168db361b
